export const mockTransactionListItem = {
  id: 690,
  parentId: null,
  transactionId: "TXCSH0015888",
  cashOrderNum: "CO-0PCJ9HBXFEWPP",
  couponOrderNum: null,
  orderStatus: "pending-maker",
  orderStatusAlias: "pending",
  orgNum: "RG-0E1ZY1T9E8879",
  orgName: "QC For Only Automation",
  subOrgNum: "SRG-0FMC6Y4NE780H",
  subOrgName: "QC for maker and checker hi",
  bankAccountUid: "cma-dbs-sgd",
  bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
  bankAccountNum: "XXXXXXX822-SGD",
  transactionType: "deposit",
  transactionCategory: "credit",
  createDo: "2026-02-04",
  effectiveDo: "2026-02-04",
  isin: null,
  currency: "SGD",
  description: "Deposit",
  submitType: "admin-draft",
  referenceNum: "Deposit",
  netAmt: 10000000,
  feesAmt: 0,
  gstAmt: 0,
  bankChargesAmt: 0,
  cashOrderAmt: 10000000,
  debit: null,
  credit: 10000000,
  files: null,
  comments: null,
  productOrderableType: null,
  orderTransactionId: null,
  bankAccountTxId: null,
  groupId: null,
  securityName: null,
  payDt: null,
  couponPaymentRate: null,
  valueOfSettledHolding: null,
  runningBal: null,
  postedTo: "Client",
  couponPayments: null,
  totalCouponAmount: null,
  parentTransactionId: null,
  inBeneficiaryAccountName: null,
  inBeneficiaryAccountNumber: null,
  needToReplaceFloatToCma: false,
};

export const mockTransactionDetail = {
  cashOrderData: {
    transactionId: "TXCSH0015888",
    cashOrderNum: "CO-0PCJ9HBXFEWPP",
    couponOrderNum: null,
    orderStatus: "pending-maker",
    orderStatusAlias: "pending",
    orgNum: "RG-0E1ZY1T9E8879",
    orgName: "QC For Only Automation",
    subOrgNum: "SRG-0FMC6Y4NE780H",
    subOrgName: "QC for maker and checker hi",
    bankAccountUid: "cma-dbs-sgd",
    bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    bankAccountNum: "XXXXXXX822-SGD",
    transactionType: "deposit",
    transactionCategory: "credit",
    createDo: "2026-02-04",
    effectiveDo: "2026-02-04",
    isin: null,
    currency: "SGD",
    description: "Deposit",
    submitType: "admin-draft",
    netAmt: 10000000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    debit: null,
    credit: 10000000,
    files: [],
    productOrderableType: null,
    orderTransactionId: null,
    bankAccountTxId: null,
    groupId: null,
    securityName: null,
    payDt: null,
    couponPaymentRate: null,
    valueOfSettledHolding: null,
    runningBal: null,
    postedTo: "Client",
    couponPayments: null,
    totalCouponAmount: null,
    parentTransactionId: null,
    inBeneficiaryAccountName: "Beneficiary",
    inBeneficiaryAccountNumber: "Beneficiary",
  },
  pendingTaskData: null,
};

export const mockTransactionList = [
  mockTransactionListItem,
  {
    ...mockTransactionListItem,
    id: 691,
    transactionId: "TXCSH0015889",
    cashOrderNum: "CO-0PCJ9HBXFEWPQ",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    transactionType: "withdrawal",
    transactionCategory: "debit",
    netAmt: 5000000,
    cashOrderAmt: 5000000,
    debit: 5000000,
    credit: null,
    description: "Withdrawal",
    referenceNum: "Withdrawal",
  },
  {
    ...mockTransactionListItem,
    id: 692,
    transactionId: "TXCSH0015890",
    cashOrderNum: "CO-0PCJ9HBXFEWPR",
    orderStatus: "pending-checker",
    orderStatusAlias: "pending",
    transactionType: "coupon-payment",
    isin: "SG1234567890",
    securityName: "Test Security Bond",
    netAmt: 2500000,
    cashOrderAmt: 2500000,
    credit: 2500000,
    description: "Coupon Payment",
    referenceNum: "Coupon Payment",
  },
];
