export const mockTransactionListItem = {
  id: 690,
  parentId: null,
  transactionId: "TXCSH0015888",
  cashOrderNum: "CO-0PCJ9HBXFEWPP",
  couponOrderNum: null,
  orderStatus: "pending-maker",
  orderStatusAlias: "pending",
  orgNum: "RG-0E1ZY1T9E8879",
  orgName: "QC For Only Automation",
  subOrgNum: "SRG-0FMC6Y4NE780H",
  subOrgName: "QC for maker and checker hi",
  bankAccountUid: "cma-dbs-sgd",
  bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
  bankAccountNum: "XXXXXXX822-SGD",
  transactionType: "deposit",
  transactionCategory: "credit",
  createDo: "2026-02-04",
  effectiveDo: "2026-02-04",
  isin: null,
  currency: "SGD",
  description: "Deposit",
  submitType: "admin-draft",
  referenceNum: "Deposit",
  netAmt: 10000000,
  feesAmt: 0,
  gstAmt: 0,
  bankChargesAmt: 0,
  cashOrderAmt: 10000000,
  debit: null,
  credit: 10000000,
  files: null,
  comments: null,
  productOrderableType: null,
  orderTransactionId: null,
  bankAccountTxId: null,
  groupId: null,
  securityName: null,
  payDt: null,
  couponPaymentRate: null,
  valueOfSettledHolding: null,
  runningBal: null,
  postedTo: "Client",
  couponPayments: null,
  totalCouponAmount: null,
  parentTransactionId: null,
  inBeneficiaryAccountName: null,
  inBeneficiaryAccountNumber: null,
  needToReplaceFloatToCma: false,
};

export const mockTransactionDetail = {
  cashOrderData: {
    transactionId: "TXCSH0015888",
    cashOrderNum: "CO-0PCJ9HBXFEWPP",
    couponOrderNum: null,
    orderStatus: "pending-maker",
    orderStatusAlias: "pending",
    orgNum: "RG-0E1ZY1T9E8879",
    orgName: "QC For Only Automation",
    subOrgNum: "SRG-0FMC6Y4NE780H",
    subOrgName: "QC for maker and checker hi",
    bankAccountUid: "cma-dbs-sgd",
    bankAccountName: "SBI DIGITAL MARKETS PTE. LTD. - (CMA)",
    bankAccountNum: "XXXXXXX822-SGD",
    transactionType: "deposit",
    transactionCategory: "credit",
    createDo: "2026-02-04",
    effectiveDo: "2026-02-04",
    isin: null,
    currency: "SGD",
    description: "Deposit",
    submitType: "admin-draft",
    netAmt: 10000000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    debit: null,
    credit: 10000000,
    files: [],
    productOrderableType: null,
    orderTransactionId: null,
    bankAccountTxId: null,
    groupId: null,
    securityName: null,
    payDt: null,
    couponPaymentRate: null,
    valueOfSettledHolding: null,
    runningBal: null,
    postedTo: "Client",
    couponPayments: null,
    totalCouponAmount: null,
    parentTransactionId: null,
    inBeneficiaryAccountName: "Beneficiary",
    inBeneficiaryAccountNumber: "Beneficiary",
  },
  pendingTaskData: null,
};

export const mockTransactionList = [
  // Original transaction - Deposit
  mockTransactionListItem,
  
  // Withdrawal transaction
  {
    ...mockTransactionListItem,
    id: 691,
    transactionId: "TXCSH0015889",
    cashOrderNum: "CO-0PCJ9HBXFEWPQ",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    transactionType: "withdrawal",
    transactionCategory: "debit",
    createDo: "2026-02-05",
    effectiveDo: "2026-02-05",
    netAmt: 5000000,
    cashOrderAmt: 5000000,
    feesAmt: 50000,
    gstAmt: 3500,
    bankChargesAmt: 100,
    debit: 5000000,
    credit: null,
    description: "Withdrawal to bank account",
    referenceNum: "WD-20260205-001",
  },
  
  // Coupon Payment transaction
  {
    ...mockTransactionListItem,
    id: 692,
    transactionId: "TXCSH0015890",
    cashOrderNum: "CO-0PCJ9HBXFEWPR",
    orderStatus: "pending-checker",
    orderStatusAlias: "pending",
    transactionType: "coupon-payment",
    transactionCategory: "credit",
    createDo: "2026-02-05",
    effectiveDo: "2026-02-06",
    isin: "SG1234567890",
    securityName: "Test Security Bond",
    netAmt: 2500000,
    cashOrderAmt: 2500000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    credit: 2500000,
    debit: null,
    description: "Coupon Payment for SG1234567890",
    referenceNum: "CP-20260205-001",
    groupId: "GT0000469",
  },
  
  // Another Deposit - USD (Draft)
  {
    ...mockTransactionListItem,
    id: 693,
    transactionId: "TXCSH0015891",
    cashOrderNum: "CO-0PCJ9HBXFEWPS",
    orderStatus: "draft",
    orderStatusAlias: "draft",
    currency: "USD",
    bankAccountNum: "XXXXXXX822-USD",
    transactionType: "deposit",
    transactionCategory: "credit",
    createDo: "2026-02-06",
    effectiveDo: null,
    netAmt: 15000,
    cashOrderAmt: 15000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    credit: 15000,
    debit: null,
    description: "Client Deposit - USD",
    referenceNum: "DEP-20260206-001",
  },
  
  // Transfer transaction
  {
    ...mockTransactionListItem,
    id: 694,
    transactionId: "TXCSH0015892",
    cashOrderNum: "CO-0PCJ9HBXFEWPT",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    transactionType: "transfer",
    transactionCategory: "debit",
    createDo: "2026-02-04",
    effectiveDo: "2026-02-04",
    netAmt: 7500000,
    cashOrderAmt: 7500000,
    feesAmt: 25000,
    gstAmt: 1750,
    bankChargesAmt: 50,
    debit: 7500000,
    credit: null,
    description: "Transfer between accounts",
    referenceNum: "TRF-20260204-001",
    groupId: "GT0000470",
  },
  
  // Another Withdrawal - smaller amount
  {
    ...mockTransactionListItem,
    id: 695,
    transactionId: "TXCSH0015893",
    cashOrderNum: "CO-0PCJ9HBXFEWPU",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    transactionType: "withdrawal",
    transactionCategory: "debit",
    createDo: "2026-02-03",
    effectiveDo: "2026-02-03",
    netAmt: 1250000,
    cashOrderAmt: 1250000,
    feesAmt: 12500,
    gstAmt: 875,
    bankChargesAmt: 50,
    debit: 1250000,
    credit: null,
    description: "Cash withdrawal",
    referenceNum: "WD-20260203-001",
  },
  
  // Deposit with fees (Draft)
  {
    ...mockTransactionListItem,
    id: 696,
    transactionId: "TXCSH0015894",
    cashOrderNum: "CO-0PCJ9HBXFEWPV",
    orderStatus: "draft",
    orderStatusAlias: "draft",
    transactionType: "deposit",
    transactionCategory: "credit",
    createDo: "2026-02-06",
    effectiveDo: null,
    netAmt: 20000000,
    cashOrderAmt: 20000000,
    feesAmt: 100000,
    gstAmt: 7000,
    bankChargesAmt: 200,
    credit: 20000000,
    debit: null,
    description: "Large deposit transaction",
    referenceNum: "DEP-20260206-002",
  },
  
  // Coupon with different org
  {
    ...mockTransactionListItem,
    id: 697,
    transactionId: "TXCSH0015895",
    cashOrderNum: "CO-0PCJ9HBXFEWPW",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    orgName: "ABC Investment Company",
    subOrgName: "Trading Division",
    transactionType: "coupon-payment",
    transactionCategory: "credit",
    createDo: "2026-02-02",
    effectiveDo: "2026-02-02",
    isin: "SG9876543210",
    securityName: "Corporate Bond Series A",
    netAmt: 3750000,
    cashOrderAmt: 3750000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    credit: 3750000,
    debit: null,
    description: "Quarterly coupon payment",
    referenceNum: "CP-20260202-001",
    groupId: "GT0000471",
  },
  
  // Pending withdrawal
  {
    ...mockTransactionListItem,
    id: 698,
    transactionId: "TXCSH0015896",
    cashOrderNum: "CO-0PCJ9HBXFEWPX",
    orderStatus: "pending-checker",
    orderStatusAlias: "pending",
    transactionType: "withdrawal",
    transactionCategory: "debit",
    createDo: "2026-02-06",
    effectiveDo: "2026-02-06",
    netAmt: 3500000,
    cashOrderAmt: 3500000,
    feesAmt: 35000,
    gstAmt: 2450,
    bankChargesAmt: 75,
    debit: 3500000,
    credit: null,
    description: "Pending withdrawal approval",
    referenceNum: "WD-20260206-001",
  },
  
  // Large deposit completed
  {
    ...mockTransactionListItem,
    id: 699,
    transactionId: "TXCSH0015897",
    cashOrderNum: "CO-0PCJ9HBXFEWPY",
    orderStatus: "completed",
    orderStatusAlias: "completed",
    transactionType: "deposit",
    transactionCategory: "credit",
    createDo: "2026-02-01",
    effectiveDo: "2026-02-01",
    netAmt: 50000000,
    cashOrderAmt: 50000000,
    feesAmt: 0,
    gstAmt: 0,
    bankChargesAmt: 0,
    credit: 50000000,
    debit: null,
    description: "Initial capital deposit",
    referenceNum: "DEP-20260201-001",
  },
];
